### ISSUE TITLE
Transformed imports contain incorrect file extension

### ISSUE THREAD

**Issue by chanceaclark** [BuilderIO/mitosis#991] opened 2023-01-18 22:59 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [X] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://stackblitz.com/edit/node-9aesvr?file=src%2Fcomponents%2Findex.ts,dist%2Freact%2Fsrc%2Fcomponents%2Findex.js

### Expected Behaviour

Typically, modern build tools will auto resolve modules when the file extension is omitted (with a proper loader/config). When running `mitosis build`, the module extension should be omitted so it can be resolved correctly.

_Expected output from `mitosis build`:_
```js
// src/components/index.js
import { default as default2 } from "./Button";
export {
  default2 as Button
};
```

### Actual Behaviour

When using a **named or default** exports for a component in an `index.{ts,js}` file, mitosis transforms on the file type extension (`Button.js`). This causes a problem when consuming the import through bundlers/transpilers causing the import to error since the exported component extension is `.jsx`.

_Actual output from `mitosis build`:_
```js
// src/components/index.js
import { default as default2 } from "./Button.js";
export {
  default2 as Button
};

### Additional Information

I've been running my built components through `esbuild` with the proper js -> jsx loader setup. Here's the build error (for others running into this):

```bash
✘ [ERROR] Could not resolve "./Button.js"

    ../dist/react/src/components/index.js:1:33:
      1 │ import { default as default2 } from "./Button.js";
```

I've traced this to these lines:
- https://github.com/BuilderIO/mitosis/blob/main/packages/cli/src/build/helpers/transpile.ts#L27-L30
- https://github.com/BuilderIO/mitosis/blob/main/packages/cli/src/build/helpers/extensions.ts#L39-L40

I tried to do due-diligence to find a similar issue, but let me know if this is a duplicate 🙏 

Regarding a path forward, I was experimenting locally with config options (e.g. `omitFileExtensions`), but not sure that is the best path forward. You could use `options[target].transpiler.format === 'esm'` to omit file extensions from imports, but very hesitant with that solution. Let me know if y'all have something better in mind.

**Comment by samijaber** [comment] 2023-01-19 14:29
Yeah, I've been fiddling with this very recently. I haven't landed on the perfect solution yet.

## ESM requires import extensions

> Typically, modern build tools will auto-resolve modules when the file extension is omitted (with a proper loader/config). When running mitosis build, the module extension should be omitted so it can be resolved correctly.

That might be true, and if we make the assumption that everyone has a build tool processing the Mitosis output, we can probably completely get rid of import path extensions. 

But I don't know if I want to make such an assumption. I bumped into a ton of different issues in the past due to the absence of explicit file extensions. They were caused by the fact that the ESM Spec _requires_ file extensions: https://nodejs.org/api/esm.html#mandatory-file-extensions. So I feel like omitting them is bad practice, especially for ESM. 

Granted, I didn't have a build tool processing the Mitosis output back then, but I think the output shouldn't need a build tool to work 🤔 


## Build tools don't transform `.jsx` import paths

This is a non-issue for all of the other extensions (vue, svelte, etc.). Also, we can use `.js` imports to refer to `.ts` files without issues. So this is only a JSX/TSX issue, and I am not sure what the best path forward is for `.jsx`/`.tsx` files...I couldn't find an answer to this.

I tried to find a build tool that will transform import paths (i.e. `import x from './X.jsx'`; -> `import x from './X.js`), but couldn't find a single one that does so (I tried `tsc`, `esbuild`, `vite`, `swc`). It seems to be fairly non-standard practice to do such a transformation.


## Current status 

The way it currently works (for me) is that:
- Mitosis will transform the import path to `Button.js`, even though the file itself is called `Button.jsx`
- My build tool compiles all `.jsx` files to `.js`, which aligns the imports with the file names. (I've tried this with both `tsc` and `vite`, and it works in both cases)

I know that this is not ideal, since we're back to me needing a build tool, and the code is now broken by default without one...

## Ideas

The options I know of are:

  1. CURRENT: mitosis has `.js` imports pointing to `.jsx` files.
  2. ONLY .js: mitosis has `.js` imports pointing to `.js` files (we used to do this, it means Mitosis is a mandatory build step for jsx files, and the user never receives plain `.jsx`)
  3. ONLY .jsx: mitosis has `.jsx` imports pointing to `.jsx` files
  4. NO extension: mitosis has no file extensions in imports, pointing to `.jsx` files
  5. Configurable: config option for JSX-based frameworks (React, React Native, Solid) that toggles between 2/4

Tallying up the cons:
1) is broken without a build tool, 
2) poor DX as the user can never see the JSX output, and mitosis is forced to make choices regarding how to build them to JS files (which might not match user preference)
3) will require a mandatory import path transformation that no build tool currently performs (AFAIK)
4) this would break ESM spec unless a build tool is bundling everything and the user publishes that output
5) ...let each person pick their poison?


Maybe I should go with 5) for now to unblock everyone....and allow options 2 + 4, as those seem like the most sensible ones.

Partially related issue: https://github.com/BuilderIO/mitosis/issues/809#issuecomment-1297287607

**Comment by chanceaclark** [comment] 2023-01-19 16:07
### ESM requires import extensions

>https://nodejs.org/api/esm.html#mandatory-file-extensions. So I feel like omitting them is bad practice, especially for ESM.

Ahh that's right, but I believe this should only be true for running inside a node environment. Just tested this locally and it looks like it needs to be an exact filename match. However, node won't be able to resolve `.jsx` file extensions even if they are left in:
![Screenshot 2023-01-19 at 10 36 27](https://user-images.githubusercontent.com/10539418/213485623-ce26f0e8-5ec6-4e2a-b705-f8dd81b52c99.png)

Even when using the `.jsx` extension in the import, there is a TypeError:
```bash
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".jsx" for ...
```

### Build tools don't transform .jsx import paths

>It seems to be fairly non-standard practice to do such a transformation.

Yeah, I'd agree that it's pretty non-standard. Like you mentioned above, it's probably not ideal and can be poor DX for consumers to understand that they need to do that. As a library maintainer myself, we have always done the transformation to `.js` for the consumers, which _would_:tm: generally resolve most of the issues here. Although, I bet y'all want to keep the `.jsx` files being exported on build 😬 

### Ideas

I think 5) is the best bet, _for now_, but I can see it not being the ideal solution for the future. To quote the spec for JSX:

>It's NOT intended to be implemented by engines or browsers.

_Source: https://github.com/facebook/jsx_

With that in mind, node isn't going to resolve that as a module. Either now or in the future, y'all might consider doing to the transpilation from `.jsx` to `.js` for the consumers (based on language options). That should be in line with ESM spec.

**Comment by samijaber** [comment] 2023-01-19 20:01
After some though, I realize that it's a fairly reasonable expectations that JSX files go through a bundling tool before being published as NPM packages (I don't think you can/should ever publish a JSX file as-is to NPM). So I'm OK dropping the file extensions for `.jsx` files, but still outputting JSX files (option 4)

**Comment by chanceaclark** [comment] 2023-01-19 20:44
@samijaber just to get some clarity and vision for what Mitosis is for, is A) the output intended to be consumed right away after build or B) is the intention to bundle/transpile the output before being published?

One of the [examples](https://github.com/BuilderIO/mitosis/tree/main/examples/talk/apps/output/react) demonstrates theoretically that the output could be published as a module after build which aligns with A). That seems to me like the output should be a `.js` file instead of `.jsx` 🤔

**Comment by samijaber** [comment] 2023-01-19 20:50
PS: The talk example was specifically for a conference talk, I wouldn't say it's representative of a real-world scenario. 

I want to keep Mitosis as lightweight and un-opinionated as possible, hence gravitating towards as little bundling/transpilation within Mitosis as possible. so I'd say B)

So far, the vast majority of use-cases for Mitosis is to publish NPM packages. I want to stick with B) until we gather enough data from users, to know if it's even feasible for Mitosis to take care of all bundling for you. There is so much at play to get bundling working for all possible Mitosis outputs, I don't know if it'll ever happen, especially given that bundling has so many nuances and configurations (different ES targets, different bundling strategies, etc.)

**Comment by chanceaclark** [comment] 2023-01-19 21:06
Gotcha! Thanks for the clarification! 

I've been exploring it for generating a headless storefront component library. Would be nice to publish without any additional steps, but fair enough to be lightweight (and to not deal with all the complexity). Thanks for taking a look into this 😄

**Closed** 2023-01-20 17:12 UTC
Labels: bug, cli
