### ISSUE TITLE
React Native - Styles not applying to <Text/> component 

### ISSUE THREAD

**Issue by dharveshmydeen15** [BuilderIO/mitosis#1514] opened 2024-07-31 07:11 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [X] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/playground/?code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJdzgodBhkKANbIo8AHhZgbIA%2Bao84GuBNMGQYFtbPVFQEhARevs8IJmgALmoSlioQ0Y9CQiW4bJwmZHQhwODVsdbvUwALHE0Acx2EWxzrGFcExvDS6ODb3JsOXCgrmA4Nlt0M4DmMeM1DjVUGBzv1BsM1l5JlAZlQ5gtRitGgAJdBMSYAQjgAElPLCoFo4IE9LkmMY4B04AAldA4XRhABq2zCmFp%2BDCAEUAO7AADWYXOLDgIHO9JA0AIZBiQugotQBJqPGh5whrU19SaRQKEkIQA

### Expected Behaviour

Styles should apply for <Text/> element also currently its applying only for <View/>

### Actual Behaviour

<Text style={styles.view1} />

**Comment by JerryWu1234** [comment] 2024-08-23 03:47
I'll check this problem

**Comment by JerryWu1234** [comment] 2024-08-26 08:26
```jsx
       <View >
        <Text style={styles.view1}>
          Hello! I can run natively in React, Vue, Svelte, Qwik, and many more
          frameworks!
        </Text>
      </View>
```
like this ?
@dharveshmydeen15

**Comment by samijaber** [comment] 2024-09-30 18:20
I don't see an issue in the playground you linked. Unclear to me what the problem is.

Closing due to lack of information

**Closed by samijaber** 2024-09-30 18:20 UTC
Labels: bug
