### ISSUE TITLE
Visual Editor VSCode Plugin renames existing export default function to MyComponent when editing Mitosis JSX file

### ISSUE THREAD

**Issue by crickkills** [BuilderIO/mitosis#217] opened 2022-03-16 17:09 UTC
**Describe the bug**
I am using the Visual Editor [VSCode plugin](https://github.com/builderio/vscode) to convert a Mitosis JSX file. If I set the main export default function name to "Button", the output code continues to use the default function name "MyComponent" instead of "Button". If I copy+paste the same source code in the live Mitosis Fiddle, the main function name is updated to use "Button" instead of "MyComponent", so the issue seems to be limited to the plugin and not reproducible in the live Fiddle.

**To Reproduce**
1. [Visit this Fiddle](https://mitosis.builder.io/?outputTab=react&code=import+%7B+useState%2C+onMount+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+default+function+Button%28props%29+%7B%0A++const+state+%3D+useState%28%7B+name%3A+null+%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++state.name+%3D+props.name+%3F+props.name+%3A+%27Default%27%3B%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cbutton%3E%0A++++++%3Cspan%3EHello+from+%3C%2Fspan%3E%0A++++++%3Cspan%3E+%7Bname%7D%3C%2Fspan%3E%0A++++++%3Cspan%3E%21%3C%2Fspan%3E%0A++++%3C%2Fbutton%3E%0A++%29%3B%0A%7D%0A) to obtain the source code. Copy the source code and paste into a file called button.lite.tsx.
2. Install the [VSCode plugin](https://github.com/builderio/vscode) in your VSCode editor.
3. Edit button.lite.tsx in VSCode and open the Builder.io plugin in the sidebar by searching "Builder" in the command palette.
4. Click "GET CODE" in the top right corner of the plugin and select the REACT tab. Notice the code in the "Render statically" panel uses the function name "MyComponent" instead of "Button".

If possible, a link to a https://mitosis.builder.io/ fiddle containing the bug: N/A

**Expected behavior**
I expect that the main export default function name in the generated output should be "Button" as in the source code, instead of the default "MyComponent". The live fiddle works as expected, so I would expect the plugin to have the same behavior.

**Screenshots**
![plugin-output-wrong](https://user-images.githubusercontent.com/871998/158645665-d07d6d04-19f9-41b4-97d3-2bb78d409b39.png)
![fiddle-output-correct](https://user-images.githubusercontent.com/871998/158645725-094bf919-8746-46fe-a6e5-5d6d56e15431.png)

**Additional context**
VSCode v1.64.1
Builder.io for VSCode plugin v0.0.9

**Comment by samijaber** [comment] 2022-03-16 20:25
Hey @crickkills! Given current resource constraints, we are not actively developing/maintaining our VSCode plugin, so it is staying in an `alpha` state for a while longer. 

I would recommend you setup a dev environment that does not require the VSCode plugin to iterate on your Mitosis components. Using `react` as an example target:
- have a `watch mitosis build` command that builds your Mitosis code and watches for changes
- add a `package.json` to your react output folder.
- use `yarn link` or `npm link`  on your react output and link it to a separate NextJS project
- import your NPM package
- run your local NextJS dev server

Using a setup like this, you should be able to essentially "hot reload" when you make a change to your mitosis components source code and see it in the browser :)
If you're having trouble seeing how this example would work, I can spend some time putting it together and sharing it.

PS: I'd also suggest you raise VSCode plugin issues in https://github.com/BuilderIO/vscode/issues so that we better keep track of them since they're not caused by bugs in the `mitosis` repo!

**Comment by samijaber** [comment] 2022-04-19 14:58
I will close this issue since it is related to a separate codebase: https://github.com/BuilderIO/vscode

**Closed by samijaber** 2022-04-19 14:58 UTC
