### ISSUE TITLE
Will There be an option to use custom library as input in near future ?

### ISSUE THREAD

**Issue by Dhananjay-JSR** [BuilderIO/mitosis#167] opened 2022-02-02 05:35 UTC
I really want to use some react only UI library on other frameworks too

**Comment by steve8708** [comment] 2022-02-02 16:21
Unfortunately this is unlikely, there are a lot of things you can do in a React library that won't easily parse and compile to other frameworks. Though this would be of HUGE value so I'll leave this open and maybe we can chip away at getting incrementally closer to this goal over time

**Comment by PatrickJS** [comment] 2022-03-15 23:35
You would need a react to mitosis json then you can mitosis to any framework

**Comment by samijaber** [comment] 2022-08-08 16:30
Closing as this is essentially a duplicate of #149, so you can follow the other issue for a conversation around this.

**Closed by samijaber** 2022-08-08 16:30 UTC
