### ISSUE TITLE
Svelteosis not working on https://mitosis.builder.io/

### ISSUE THREAD

**Issue by SOG-web** [BuilderIO/mitosis#1414] opened 2024-04-29 21:58 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/

### Expected Behaviour

It should generate output to other frameworks

### Actual Behaviour

It not currently working and No proper docs for using svelteosis. Also I tried using angularToMittosis, it not picking up the template, i am ready to work on the angular part if I get to understand how it all works together, am just getting to mess around with AST, so am not really good at it yet, but am ready to learn and do a fix if am pointed to the right resources. Thanks

**Comment by samijaber** [comment] 2024-05-03 15:46
duplicate of https://github.com/BuilderIO/mitosis/issues/1327

**Closed by samijaber** 2024-05-03 15:46 UTC
Labels: bug
