### ISSUE TITLE
React output does not preserve JSX

### ISSUE THREAD

**Issue by hasanhaja** [BuilderIO/mitosis#900] opened 2022-11-12 11:10 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhwo6GMigHb7h5wADwMMIIGEJqmTMDaANYAvAi2rokAfHAOEE4cUTFx8amE6QjZufgyMITBPGER6YHOkoRAA%3D%3D

### Expected Behaviour

The expected behavior is the same as the fiddle linked above.

### Actual Behaviour

However, when using the CLI the output is not JSX. It is `React.createElement(...)`.

**Comment by hasanhaja** [comment] 2022-11-12 11:12
@samijaber I'm happy to work on this issue. Would you be able to assign me to it?

Do you have any pointers on how I can get started on this

**Comment by samijaber** [comment] 2022-11-12 13:09
Definitely. I appreciate you being open to contributing a fix for this! 🙌🏽 

The issue is that we're making this call here: https://github.com/BuilderIO/mitosis/blob/2075f11eb4f769063e742386af560a71ab9984a2/packages/cli/src/build/build.ts#L321-L344

Setting `typescript: true` in `mitosis.config.js` will disable transpilation, but that (rightfully) doesn't make sense. We should get rid of this completely to make React output consistent with others.

Only caveat is that `transpile` also takes care of transforming certain import strings. We still want to preserve that behaviour. So I would replace it with a call to `transpiled = transformImports(target, options)(transpiled)`.

**Comment by samijaber** [comment] 2022-11-12 13:11
Actually, I just ran through this logic: I think you can simply remove the entire block I linked to altogether and not replace it with any call to `transformImports` whatsoever!

**Comment by samijaber** [comment] 2022-11-14 12:54
@hasanhaja I happened to be in that function cleaning up some other bugs, and went ahead and solve this one for ya

**Comment by hasanhaja** [comment] 2022-11-14 13:09
@samijaber Ah thank you! I appreciate it. Shall I close this now?

**Closed** 2022-11-14 13:56 UTC
Labels: bug, good first issue
