### ISSUE TITLE
Vue SVG: fillRule and fillOpacity should convert to fill-rule/ fill-opacity 

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#873] opened 2022-11-04 05:53 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [X] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [X] Stencil
- [X] Svelte
- [X] Vue
- [X] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMAi6BmBDZAGxgAUoIxU4BfOHckOAcgAEAjZYQgE3SgDpgEAPQhgMCKmComAKFnoAHpFhxe%2BIvBzIAdgGMYQnXADCAC3R6A1gDEuhABRhylAJSJ5cOFHQxkUYwdZLy8AHlQANwBzYJCvRRBCHVQAXgAiMxgYMAAuYWEAdyL%2BAoBmfmgo4QAmAAZ64UiotNivAD5WkNCount0nQgddDTewkIAJSJ0dPQI9AHubjSOuLjQsDwYM1HCdIBiG0ORnHsAeQ29cQBPFIRa%2FgBWWm50gFlauFqzauqIn4AJWoALxGFDwlxgNzu%2FFqAEZaMIVqtQsIokiwo1okjXLJqLIgA

### Expected Behaviour

```js
<g fill="none" fillRule="evenodd">
  <path fill="#FFF" fillOpacity={0.5} d="M0 0h22v22H0z" opacity={0.01} />
</g>
```
`fillRule` should convert to `fill-rule`
`fillOpaticy` should convert to `fill-opaticy`

### Actual Behaviour

`fillRule` should convert to `fillRule`
`fillOpaticy` should convert to `fillOpaticy`

**Comment by samijaber** [comment] 2022-11-04 17:54
This is somewhat a duplicate of https://github.com/BuilderIO/mitosis/issues/526: we had a long discussion there and decided to:

- make Mitosis use camelcased attributes, e.g. `fillRule`
- add logic to all generators (except solid/react) to lowercase those attributes


This is actually not a bug at the moment because `fillRule` is not a valid attribute in Mitosis JSX types: it is currently expecting you to write `fillrule`, and you can see that the fiddle complains about it being invalid:

<img width="702" alt="CleanShot 2022-11-04 at 14 54 21@2x" src="https://user-images.githubusercontent.com/1393142/200043384-30708f4e-d605-4c51-aed3-d2b1a068dc5a.png">

Closing as it's a duplicate of #526

**Closed by samijaber** 2022-11-04 17:54 UTC
Labels: bug
