### ISSUE TITLE
Document custom state hooks

### ISSUE THREAD

**Issue by TzviPM** [BuilderIO/mitosis#1226] opened 2023-07-18 14:21 UTC
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### What problem does this feature solve?

I was not able to find documentation for custom useX functions, nor could I get it working in my project. I’d like to be able to create state helpers that expose functionality to be used by multiple components.

### What does the proposed API look like?

Here’s an example for a counter:

```
export function useCounter(start, step, interval) {
  const state = useStore({
    count: start,
    timer: undefined,
  });

  onMount(() => {
    state.count = start;
    state.timer = setInterval(() => {
      state.count = state.count + step;
    }, interval);
  });

  onUnMount(() => {
    clearInterval(state.timer);
    state.timer = undefined;
  });

  return state;
}
```

This could be used like this:

```
export default function Counter() {
  const state = useCounter(1, 1, 1000);

  return <div>Count is: {state.count}</div>;
}
```

### Additional Information

I would also be fine with documenting that this is not possible currently as sufficient to resolve this issue, and then finding a better venue for a design discussion.

**Comment by samijaber** [comment] 2023-07-18 17:58
Not currently supported. Duplicate of #548

**Closed by samijaber** 2023-07-18 17:58 UTC
Labels: enhancement

**Comment by TzviPM** [comment] 2023-07-21 02:55
Please either post link to where this is documented clearly or reopen. The issue was not to add the feature, but to document it clearly. If it’s not supported, that’s fine, but that’s not currently documented clearly

**Comment by TzviPM** [comment] 2023-07-23 04:41
@mhevery os this the type of community you stand by for @BuilderIO? I expected that a company trying to push forward open source on the web with Qwik, Mitosis, Partytown, and others would be more welcoming of new contributors and address their concerns and offers to help rather than close issues abruptly without resolution.
