### ISSUE TITLE
React generator fails when there is a comment with a single quote

### ISSUE THREAD

**Issue by ja-rivas** [BuilderIO/mitosis#613] opened 2022-08-03 19:56 UTC
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC%2BcAZlBCHAEQACARssADYAm6UAdMBAPQjAwIqYKioBuAFAT0AD0iw4bEjmRN4JZADsAxjG6a4AWQCeAYQqRN6TTAAUYcmFQBKRBLhxtETangBtTRwQdAAaOAwYADkg9ABdOABeFAxsPHRbKmx0ADd0KmdJd1ItXX1FCEwKdBgAC2BNAHNbVwQijx4eOAAVOtRPHE0Acng6Ai9wZnQWNs9vVAgmdA4mCCbBnpE4TZw4fF9BgqLCKQ8oauQoA1sZgB4WYGyAPhmPG%2FqwZBgXj09UVASEK0fsCfl4VlAAFzUOhMZB5ELfDyEY4gn7ZHCw9AAwLBFGouDeUw1AYNLEIWw5awwVwJR7harRYIU3I2Di4KCkmAcdGY5x44E8Z6ogAS6CYKwAhHAAJL9AxQLRbAwAJXQOF0YQAanCwpUmMAWGFoHAADLAACOjBYEtuPHuTyKh0IQA%3D%3D%3D

### Expected Behaviour

```jsx
import * as React from "react";
import { useState } from "react";

export default function MyComponent(props) {
  const [name, setName] = useState(() => "Steve");

  function doSomething() {
    // This can't be compiled
    console.log("This is a test");
  }

  return (
    <>
      <div>
        <input
          className="input"
          value={name}
          onChange={(event) => setName(event.target.value)}
        />
        Hello! I can run in React, Vue, Solid, or Liquid!
      </div>
      <style jsx>{`
        .input {
          color: blue;
        }
      `}</style>
    </>
  );
}

```

### Actual Behaviour

```jsx
import * as React from "react";
import { useState } from "react";

export default function MyComponent(props) {
  const [name, setName] = useState(() => "Steve");

  function doSomething() {
    // This cant be compiled
    console.log("This is a test");
  }

  return (
    <>
      <div>
        <input
          className="input"
          value={name}
          onChange={(event) => setName(event.target.value)}
        />
        Hello! I can run in React, Vue, Solid, or Liquid!
      </div>
      <style jsx>{`
        .input {
          color: blue;
        }
      `}</style>
    </>
  );
}
```

### Additional Information

I haven't found the issue in other generators, only React.

**Comment by samijaber** [comment] 2022-08-08 13:18
Thanks for sharing another instance of this. Closing as a duplicate of #250

**Closed by samijaber** 2022-08-08 13:18 UTC
Labels: bug
